web_body/mysite/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('polls/', include('polls.urls', namespace='polls')),
    path('admin/', admin.site.urls),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_body/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.subject_list, name='subject-list'),
    path('add', views.add_subject, name='add-subject'),
    path('detail/<int:subject_id>/', views.subject_detail, name='subject-detail'),
    path('update_mgt/<int:subject_id>/', views.update_mgt, name='update-mgt'),
    path('predict_shape/<int:subject_id>/', views.predict_shape, name='predict-shape'),
    path('predict_measure/<int:subject_id>/', views.predict_measure, name='predict-measure'),
    path('delete_subject/<int:subject_id>/', views.delete_subject, name='delete-subject'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

web_body/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.core.files.storage import FileSystemStorage
import json

mids = ['m_breast_depth', 'm_cross_breast', 'm_circ_bust',
        'm_circ_waist', 'm_circ_hip', 'm_len_front_body',
        'm_len_half_girth', 'm_len_bikini_girth', 'm_len_full_girth', 'm_circ_neck',
        'm_circ_upperbust', 'm_circ_underbust', 'm_circ_highhip',
        'm_circ_thigh', 'm_circ_knee', 'm_circ_upperarm', 'm_circ_elbow',
        'm_circ_wrist', 'm_shoulder_to_bust', 'm_len_upperarm',
        'm_len_sleeve', 'm_len_waist_knee', 'm_len_skirt_waist_to_hem']

def _default_measure_json():
    measures = dict((id, -1) for id in mids)
    return _measure_to_json(measures)

def _json_to_measure(json_str):
    return json.loads(json_str)

def _measure_to_json(measures):
    return json.dumps(measures)

class Subject(models.Model):
    name = models.CharField(max_length=200)
    gender = models.CharField(max_length=200, choices=[('male','m'), ('female', 'f')], default='female')
    height = models.FloatField(default=1.5)
    measure_gt = models.CharField(max_length=10000, default = _default_measure_json())
    measure_pred = models.CharField(max_length=10000, default = _default_measure_json())
    img_f  = models.ImageField(upload_to='images')
    img_s =  models.ImageField(upload_to='images')

    img_sil_f =  models.ImageField(upload_to='body_result_sil', blank=True)
    img_sil_s =  models.ImageField(upload_to='body_result_sil', blank=True)

    img_result          = models.ImageField(upload_to='body_result_viz', blank=True)
    img_measure_viz  = models.ImageField(upload_to='body_result_viz', blank=True)

    mesh_path =  models.FilePathField(match = "*.obj", blank=True)

    # def __str__(self):
    #     return self.name

    @property
    def measures_gt(self):
        return _json_to_measure(self.measure_gt)

    @measures_gt.setter
    def measures_gt(self, measures):
        self.measure_gt = _measure_to_json(measures)

    @property
    def measures_pred(self):
        return _json_to_measure(self.measure_pred)

    @measures_pred.setter
    def measures_pred(self, measures):
        self.measure_pred = _measure_to_json(measures)

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

web_body/polls/forms.py
from django import forms
from .models import Subject

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ('name', "height", "gender", 'img_f', 'img_s')

web_body/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.shortcuts import redirect
from django.conf import settings
from .models import Choice, Question, Subject
from PIL import Image
from pathlib import Path
from skimage.io import imread
from io import BytesIO
from .inference import infer_mesh, infer_mesurement, build_shape_visualization
from common.obj_util import export_mesh, import_mesh_obj
from .forms import SubjectForm
from django.core.files import File
import numpy as np

def add_subject(request):
    if request.method == 'POST':
        form = SubjectForm(request.POST, request.FILES)
        if form.is_valid():
            sub = form.save()
            return redirect('polls:subject-detail', subject_id=sub.id)
    else:
        form = SubjectForm()

    return render(request, 'polls/add_subject.html', {
        'form': form
    })

def delete_subject(request, subject_id):
    sub = Subject.objects.get(id=subject_id)
    sub.delete()
    return redirect("polls:subject-list")

def subject_detail(request, subject_id):
    sub = Subject.objects.get(id=subject_id)
    return render(request, 'polls/subject_detail.html', {'subject':sub})

def predict_shape(request, subject_id):
    sub = Subject.objects.get(id=subject_id)
    media_dir = Path(settings.MEDIA_ROOT)
    img_f = imread(sub.img_f.path)
    img_s = imread(sub.img_s.path)
    gender_val = 0 if sub.gender in ['f', 'female'] else 1

    verts, triangles, sil_f, sil_s = infer_mesh(img_f, img_s, sub.height, gender_val)
    sil_f_rgb = np.dstack([sil_f, sil_f, sil_f])
    sil_s_rgb = np.dstack([sil_s, sil_s, sil_s])

    #save results
    mesh_path = media_dir/Path(f'body_result_mesh/{Path(sub.img_f.path).stem}_shape.obj')
    sub.mesh_path = str(mesh_path)
    export_mesh(mesh_path, verts, triangles)

    blob = BytesIO()
    sil_f_pil = Image.fromarray(sil_f_rgb)
    sil_f_pil.save(blob, 'JPEG')
    sub.img_sil_f.save(f'{Path(sub.img_f.path).stem}_sil_f.jpg', File(blob), save=False)

    blob = BytesIO()
    sil_s_pil = Image.fromarray(sil_s_rgb)
    sil_s_pil.save(blob, 'JPEG')
    sub.img_sil_s.save(f'{Path(sub.img_s.path).stem}_sil_s.jpg', File(blob), save=False)

    img_viz = build_shape_visualization(verts, sil_f_rgb, sil_s_rgb)
    img_viz_pil = Image.fromarray(img_viz)
    blob = BytesIO()
    img_viz_pil.save(blob, 'JPEG')
    sub.img_result.save(f'{Path(sub.img_f.path).stem}_viz.jpg', File(blob), save=False)

    sub.save()

    return redirect('polls:subject-detail', subject_id=sub.id)

def predict_measure(request, subject_id):
    sub = Subject.objects.get(id=subject_id)
    obj_path = Path(sub.mesh_path)
    if obj_path.exists() and Path(sub.img_sil_f.path).exists() and Path(sub.img_sil_s.path).exists():
        verts, triangles = import_mesh_obj(obj_path)

        new_measures, contours = infer_mesurement(verts, sub.height)

        #update measurement
        cur_measure = sub.measures_pred
        for key, value in new_measures.items():
            if key in cur_measure.keys():
                cur_measure[key] = value
        sub.measures_pred = cur_measure

        #build measure visualization
        img_sil_f = imread(sub.img_sil_f.path)
        img_sil_s = imread(sub.img_sil_s.path)
        img_measure_viz = build_shape_visualization(verts, img_sil_f, img_sil_s, measure_contours=contours, ortho_proj=True, body_opacity=0.5)

        #save visualization
        img_viz_pil = Image.fromarray(img_measure_viz)
        blob = BytesIO()
        img_viz_pil.save(blob, 'JPEG')
        sub.img_measure_viz.save(f'{Path(sub.img_f.path).stem}_viz.jpg', File(blob), save=False)

        sub.save()

    return redirect('polls:subject-detail', subject_id=sub.id)

#measure update
def update_mgt(request, subject_id):
    if request.method == 'POST':
        sub = Subject.objects.get(id = subject_id)
        if sub:
            cur_measures = sub.measures_gt
            for k in cur_measures.keys():
                if k in request.POST:
                    cur_measures[k] = request.POST[k]
                else:
                    print(f'missing value for measure key {k}')
            sub.measures_gt = cur_measures
            sub.save()
        return redirect('polls:subject-detail', subject_id=sub.id)
    else:
        subjects = Subject.objects.all()
        sub = subjects[0]
        return render(request, 'polls/subject_m_update.html', {'subject':sub})

def subject_list(request):
    subjects = Subject.objects.all()
    return render(request, 'polls/subject_list.html', {'subjects':subjects})

def add_subject_(request):
    if request.method == 'POST':
        file_f = request.FILES['img_front']
        file_s = request.FILES['img_side']
        gender = 0 if request.POST['gender'] == 'women' else 1
        height = float(request.POST['height'])
        gender = float(gender)

        img_f_bytes = file_f.read()
        img_s_bytes = file_s.read()
        img_f = Image.open(io.BytesIO(img_f_bytes))
        img_s = Image.open(io.BytesIO(img_s_bytes))
        path = Path('/media/D1/data_1/projects/Oh/codes/web_body/polls/static/polls/images/')
        path_f = path/'kori_f.jpeg'
        path_s = path/'kori_s.jpeg'
        img_f.save(path_f)
        img_s.save(path_s)

        measures, img_body_viz = get_mesurement(img_f_bytes, img_s_bytes, height=height, gender = gender)

        img_body  = Image.fromarray(img_body_viz)
        path_body = path/'kori_body.jpeg'
        img_body.save(path_body)
        context = {}
        context['img_f_src'] = 'kori_f.jpeg'
        context['img_s_src'] = 'kori_s.jpeg'
        context['img_body_src'] = 'kori_body.jpeg'
        context['measuredict'] = measures
        return render(request, 'polls/add_subject.html', context)
    else:
        return render(request, 'polls/add_subject.html')

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    #context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Subject.objects.all()

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

web_body/polls/templates/polls/add_subject.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <link rel="stylesheet" href="/static/style.css">
    <title>body prediction by TheOhZone</title>
  </head>
  <body>
  <h1 class="h3 mb-3 font-weight-normal">input information</h1>
    <form class="form-signin" method=post enctype=multipart/form-data >
        {% csrf_token %}
        <table>
            <tbody>
                <tr>
                    <th> <label for="img_f">front image</label></th>
                    <th> <input type ="text" name="name" id="name" required></th>
                </tr>
                <tr>
                    <th><label for="img_f">front image</label></th>
                    <th><input type="file" name="img_f" class="form-control-file" id="img_f" required></th>
                </tr>
                <tr>
                    <th><label for="img_s">side image</label></th>
                    <th><input type="file" name="img_s" class="form-control-file" id="img_s" required></th>
                </tr>
                <tr>
                    <th><label for="height">height</label></th>
                    <th><input type="number" id = "height" name="height" value = "1.524" min="0.4" max="3.0" step="0.001" required></th>
                </tr>
                <tr>
                    <th><label for="gender-select">gender</label></th>
                    <th>
                        <select name="gender" id ="gender-select">
                            <option value="female" selected>female</option>
                            <option value="male">male</option>
                        </select>
                    </th>
                </tr>
                <tr>
                    <th></th>
                    <th><button class="btn btn-lg btn-primary btn-block" type="submit">add</button></th>
                </tr>
            </tbody>
        </table>
        <!--<p class="mt-5 mb-3 text-muted">Built using Pytorch, Flask and Love</p>-->
    </form>
    <script src="//code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="//stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script type="text/javascript">
      $('.form-control-file').bind('change', function() {
          let fileSize = this.files[0].size/1024/1024; // this gives in MB
          if (fileSize > 10) {
            $("#inputfile").val(null);
            alert('file is too big. images more than 10MB are not allowed')
            return
          }

          let ext = $('#inputfile').val().split('.').pop().toLowerCase();
          if($.inArray(ext, ['jpg','jpeg']) == -1) {
            $("#inputfile").val(null);
            alert('only jpeg/jpg files are allowed!');
          }
      });
    </script>
    <!-- Github Ribbon Start-->
    <!--     <a href="https://github.com/avinassh/pytorch-flask-api-heroku" class="github-corner"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#0E2E3B; color:#FFFFFF; position: absolute; top: 0; border: 0; right: 0;"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>-->
    <!-- Github Ribbon End-->
  </body>
</html>

web_body/polls/templates/polls/body_result.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <link rel="stylesheet" href="/static/style.css">
    <title>Body Prediction by TheOhZone</title>
  </head>
  <body class="text-center">
    {% load static %}
    {% static "" as baseurl%}
    <div><img src="{{baseurl}}/polls/images/{{img_f_src}}" height="300"></div>
    <div><img src="{{baseurl}}/polls/images/{{img_s_src}}" height="300"></div>
    <div><img src="{{baseurl}}/polls/images/{{img_body_src}}" height="300"></div>
    <div>
      <table style="width:100%">
        <tr>
          <th>measurement_id</th> <th>value(in meter)</th>
        </tr>
        {% for k,v in measuredict.items %}
        <tr>
          <th>{{k}}</th > <th>{{v}}</th >
        </tr>
        {% endfor %}
      </table>
    </div>
    <script src="//code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="//stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <!-- Github Ribbon Start-->
    <a href="https://github.com/avinassh/pytorch-flask-api-heroku" class="github-corner"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#0E2E3B; color:#FFFFFF; position: absolute; top: 0; border: 0; right: 0;"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>
    <!-- Github Ribbon End-->
  </body>
</html>

web_body/polls/templates/polls/index_.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

web_body/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

web_body/polls/templates/polls/subject_detail.html
<form action="{% url 'polls:subject-list' %}" method="GET">
  {% csrf_token %}
  <button type="submit">back to subject listing</button>
</form>

<h1>{{ subject.name }}</h1>

<h2>input images</h2>
<img src="{{ subject.img_f.url }}" alt="front image" style="width:100px;">
<img src="{{ subject.img_s.url }}" alt="front image" style="width:100px;">

<h2>result visualizations</h2>
<table>
    <thead>
        <tr>
            <th>3d shape</th>
            <th>3d shape with measurements</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>
                {% if subject.img_result %}
                <img src="{{ subject.img_result.url }}" style="height:300px;">
                {% endif %}
            </th>
            <th>
                {% if subject.img_measure_viz %}
                <img src="{{ subject.img_measure_viz.url }}" style="height:300px;">
                {% endif %}
            </th>
        </tr>
        <tr>
            <th>
                <form action="{% url 'polls:predict-shape' subject.id %}" method="POST">
                {% csrf_token %}
                    <button type="submit">predict 3d shape</button>
                </form>
            </th>
            <th>
                <form action="{% url 'polls:predict-measure' subject.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit">predict measurements</button>
                </form>
            </th>
        </tr>
    </tbody>
</table>

<h2>measurement detail</h2>

<table class="table mb-0">
<thead>
    <tr>
        <th>measure_id</th>
        <th>groundtruth</th>
        <th>prediction</th>
    </tr>
</thead>
<tbody>
  {% for k,v in subject.measures_gt.items %}
    <tr>
        <th>{{k}}</th>
        <th>{{v|floatformat:2}}</th>
        <th>{{subject.measures_pred|dict_key:k|floatformat:2}}</th>
        <th>{{subject.measures_pred|dict_key:k|err_str:v}}</th>
    </tr>
  {% endfor %}
    <tr>
        <th></th>
        <th>
            <form action="{% url 'polls:update-mgt' subject.id %}" method="GET">
                <button type="submit">edit GT</button>
            </form>
        </th>
        <th></th>
    </tr>
</tbody>
</table>

web_body/polls/templates/polls/subject_list.html
{% block content %}

{% block content_header %}
<h2>Subjects</h2>
{% endblock %}

<form action="{% url 'polls:add-subject' %}" method="POST">
  {% csrf_token %}
  <button type="submit">add new subject</button>
</form>

<table class="table mb-0">
  <thead>
    <tr>
      <th>id</th>
      <th>img_f</th>
      <th>img_s</th>
      <th>name</th>
      <th>gender</th>
      <th>height</th>
      <th>detail</th>
      <th>delete</th>
    </tr>
  </thead>
  <tbody>
    {% load static %}
    {% static "" as baseurl%}
    {% for subject in subjects %}
      <tr>
        <td>{{ subject.id }}</td>
        <td>
          {% if subject.img_f %}
            <img src="{{ subject.img_f.url }}" style="width:32px;">
          {% else %}
            <span class="text-muted">no image</span>
          {% endif %}
        </td>
        <td>
          {% if subject.img_s %}
            <img src="{{ subject.img_s.url }}"  style="width:32">
          {% else %}
            <span class="text-muted">no image</span>
          {% endif %}
        </td>
        <td>{{ subject.name }}</td>
        <td>{{ subject.gender }}</td>
        <td>{{ subject.height }}</td>
        <td>
          <form action="{% url 'polls:subject-detail' subject.id %}" method="GET">
            {% csrf_token %}
            <button type="submit">detail</button>
          </form>
        </td>
        <td>
          <form action="{% url 'polls:delete-subject' subject.id %}" method="POST">
            {% csrf_token %}
            <button type="submit">delete</button>
          </form>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

web_body/polls/templates/polls/subject_m_update.html
{% block content %}
  <h2>edit ground truth measures</h2>
  <table>
    <tr>
      <th>
          <form method="post">
          {% csrf_token %}
          <table>
            <thead>
              <tr>
                <th>measure_id</th>
                <th>value</th>
                <th>color</th>
              </tr>
            </thead>
            <tbody>
            {% for k,v in subject.measures_gt.items %}
              <tr>
                <th>{{k}}</th>
                <th><input type="number" id = "{{k}}" name="{{k}}" value = "{{v}}" max="2.5" step="0.001"></th>
                <th>
                  <div style="background-color:{{k|measure_color}};padding:7px;"></div>
                </th>
              </tr>
            {% endfor %}
              <tr>
                <th></th>
                <th><button type="submit" class="btn btn-primary">update GT measuremnts</button></th>
              </tr>
            </tbody>
          </table>
        </form>
      </th>
      <th>
        {% if subject.img_measure_viz %}
        <img src="{{ subject.img_measure_viz.url }}" style="height:600px;">
        {% endif %}
      </th>
    </tr>
  </table>

{% endblock %}